# Generated by Django 5.2 on 2025-04-24 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('user', 'todo_name')},
        ),
    ]
